pipeline {
    agent any

    environment {
        AWS_DEFAULT_REGION = 'ap-south-1'
    }

    stages {
        stage('Terraform Init & Apply') {
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-creds']]) {
                    dir('cicd-pipeline/terraform') {
                        sh 'terraform init'
                        sh 'terraform apply -auto-approve'
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('cicd-pipeline'){
                sh 'docker build -t my-web-app .'
            }
        }
        }

        stage('Deploy Container') {
            steps {
                sh 'docker run -d -p 9090:80 my-web-app'
            }
        }
    }
}
